theme: Midnight
title: Gopika Kayanikunnath
description: PhD Candidate
             Joint Degree Program
             Department of Physics
             IIT Hyderabad, Telengana, India
             Centre for Astrophysics and Supercomputing (CAS)
             Swinburne University, Melbourne, VIC, Australia
